name: Build projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Qodana Scan
      uses: JetBrains/qodana-action@v5.0.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Build
      run: |
        pnpm --filter=* install
        pnpm --filter=* run build:prod
